/**
 * Git hook installation utility
 * Installs git hooks for automatic documentation sync
 */

import { promises as fs } from 'fs';
import { join } from 'path';

export interface GitHookInstallOptions {
  projectRoot?: string;
  force?: boolean;
}

/**
 * Install git hooks for Auto-Doc-Sync
 */
export async function installGitHooks(options: GitHookInstallOptions = {}): Promise<void> {
  const projectRoot = options.projectRoot || process.cwd();
  const gitHooksDir = join(projectRoot, '.git', 'hooks');
  
  // Check if .git directory exists
  try {
    await fs.access(gitHooksDir);
  } catch {
    throw new Error('Not a git repository. Please run this command from a git repository root.');
  }

  console.log('Installing Auto-Doc-Sync git hooks...\n');

  // Post-commit hook
  await installPostCommitHook(gitHooksDir, projectRoot, options.force);
  
  // Pre-push hook
  await installPrePushHook(gitHooksDir, projectRoot, options.force);
  
  console.log('\n✅ Git hooks installed successfully!');
  console.log('\nThe following hooks are now active:');
  console.log('  - post-commit: Automatically syncs documentation after commits');
  console.log('  - pre-push: Validates documentation before pushing');
}

/**
 * Install post-commit hook
 */
async function installPostCommitHook(
  gitHooksDir: string, 
  projectRoot: string, 
  force?: boolean
): Promise<void> {
  const hookPath = join(gitHooksDir, 'post-commit');
  
  // Check if hook already exists
  if (!force) {
    try {
      await fs.access(hookPath);
      console.log('⚠️  post-commit hook already exists. Use --force to overwrite.');
      return;
    } catch {
      // Hook doesn't exist, proceed with installation
    }
  }

  const hookContent = `#!/bin/sh
# Auto-Doc-Sync post-commit hook
# Auto-generated by Auto-Doc-Sync System
# This hook automatically syncs documentation after each commit

echo "🔄 Running Auto-Doc-Sync..."

# Run the documentation sync
node "${projectRoot}/dist/cli.js" --trigger=git-hook --reason="Post-commit documentation sync"

# Always exit 0 to not block commits even if sync fails
exit 0
`;

  await fs.writeFile(hookPath, hookContent, { mode: 0o755 });
  console.log('✅ Installed post-commit hook');
}

/**
 * Install pre-push hook
 */
async function installPrePushHook(
  gitHooksDir: string, 
  projectRoot: string, 
  force?: boolean
): Promise<void> {
  const hookPath = join(gitHooksDir, 'pre-push');
  
  // Check if hook already exists
  if (!force) {
    try {
      await fs.access(hookPath);
      console.log('⚠️  pre-push hook already exists. Use --force to overwrite.');
      return;
    } catch {
      // Hook doesn't exist, proceed with installation
    }
  }

  const hookContent = `#!/bin/sh
# Auto-Doc-Sync pre-push validation hook
# Auto-generated by Auto-Doc-Sync System
# This hook validates documentation is up-to-date before pushing

echo "📋 Validating documentation..."

# Run documentation validation
node "${projectRoot}/dist/cli.js" validate-docs

# Exit with validation result (blocks push if validation fails)
exit $?
`;

  await fs.writeFile(hookPath, hookContent, { mode: 0o755 });
  console.log('✅ Installed pre-push hook');
}

/**
 * Uninstall git hooks
 */
export async function uninstallGitHooks(options: GitHookInstallOptions = {}): Promise<void> {
  const projectRoot = options.projectRoot || process.cwd();
  const gitHooksDir = join(projectRoot, '.git', 'hooks');
  
  console.log('Uninstalling Auto-Doc-Sync git hooks...\n');

  const hooks = ['post-commit', 'pre-push'];
  let removed = 0;

  for (const hookName of hooks) {
    const hookPath = join(gitHooksDir, hookName);
    
    try {
      const content = await fs.readFile(hookPath, 'utf-8');
      
      // Only remove if it's our hook
      if (content.includes('Auto-Doc-Sync')) {
        await fs.unlink(hookPath);
        console.log(`✅ Removed ${hookName} hook`);
        removed++;
      } else {
        console.log(`⚠️  ${hookName} hook exists but was not created by Auto-Doc-Sync`);
      }
    } catch {
      console.log(`ℹ️  ${hookName} hook not found`);
    }
  }

  if (removed > 0) {
    console.log(`\n✅ Uninstalled ${removed} git hook(s)`);
  } else {
    console.log('\nℹ️  No Auto-Doc-Sync git hooks found');
  }
}

/**
 * Check git hook installation status
 */
export async function checkGitHooks(options: GitHookInstallOptions = {}): Promise<void> {
  const projectRoot = options.projectRoot || process.cwd();
  const gitHooksDir = join(projectRoot, '.git', 'hooks');
  
  console.log('Checking Auto-Doc-Sync git hooks...\n');

  const hooks = ['post-commit', 'pre-push'];
  let installed = 0;

  for (const hookName of hooks) {
    const hookPath = join(gitHooksDir, hookName);
    
    try {
      const content = await fs.readFile(hookPath, 'utf-8');
      
      if (content.includes('Auto-Doc-Sync')) {
        console.log(`✅ ${hookName}: Installed`);
        installed++;
      } else {
        console.log(`⚠️  ${hookName}: Exists but not managed by Auto-Doc-Sync`);
      }
    } catch {
      console.log(`❌ ${hookName}: Not installed`);
    }
  }

  console.log(`\n${installed}/${hooks.length} hooks installed`);
  
  if (installed < hooks.length) {
    console.log('\nRun "auto-doc-sync install-hooks" to install missing hooks');
  }
}
